import { writable } from "svelte/store";

export let mainMenu = writable(1)
export let prevMenu = writable(0)
export let totalRec = writable(19)

export let pegawaiContext = writable(false)
export let petugas_context = writable(false)

// Modal Context
export let modal_kepentingan_context = writable(false)
export let modal_penyelesaian_status = writable(false)

export let searchBox = writable('albaruk')
export let newDataContainer = writable()

export let petugas_value = writable('all')
export let modal_kategori = ["Orang Pribadi","Badan", "Instansi Pemerintah"]


export let petugas = writable([
        {nama : 'Azriel', value:"Azriel Situmorang", nip : '817931767'},
        {nama : 'Adila', value:"Adila", nip : '810202918'},
        {nama : 'Wiji', value:"M. Wiji Kurniawan", nip : '06002942'},
        {nama : 'Satrio', value:"Satrio K.I.W", nip : '060075288'},
    ]
)

export let kepentinganDialogue = [
  "Ereg (Asistensi Pendaftaran NPWP / Cetak Ulang)",
  "SPT Tahunan (EFIN / E-filing / E-form)",
  "SPT Masa (e-Bupot / SPT Masa PPh 21)",
  "Efaktur (PPN)",
  "Permohonan (Pengukuhan PKP / Perubahan Data / NE / etc)",
  "Billing",
  "Permintaan sertifikat efaktur mengalami error saat koneksi internet / database gagal dikelola, captcha salah, sertifikat tidak berhasil diimport, kendala jaringan saya bosan hidup dan tidak suka dengan tempat terkutuk ini",
  "Tax filing for ABC Corp completed successfully",
  "database gagal dikelola, captcha salah, sertifikat tidak berhasil diimport, kendala jaringan saya bosan hidup dan tidak suka dengan tempat terkutuk ini",
  "gagal dikelola, captcha salah, sertifikat tidak berhasil diimport, kendala jaringan saya bosan hidup dan tidak suka dengan tempat terkutuk ini",
  " koneksi internet / database gagal dikelola, captcha salah, sertifikat tidak berhasil diimport, kendala jaringan saya bosan hidup dan tidak suka dengan tempat terkutuk ini",
  "efaktur mengalami error saat koneksi internet / database gagal dikelola, captcha salah, sertifikat tidak berhasil diimport, kendala jaringan saya bosan hidup dan tidak suka dengan tempat terkutuk ini",
]

export let addNewContainer = writable({
      _id : "",
      pic_name : "",
      pic_nip : "",
      pelayanan_kepentingan : "",
      pelayanan_desc : "",
      id_npwp : "",
      id_nama: "",
      id_alamat : "",
      id_nohp : "",
      id_nik : "",
      id_klu : "",
      id_email : "",
      id_kontak_lain : "",
      id_kategori : "Orang Pribadi",
      pelayanan_status : "",
      pelayanan_tags : [], 
      pelayanan_reminder : "",
      pelayanan_doc_url : "",
      pelayanan_history : []
})

export let uploadFileContainer = writable([
  // {name :"learns to fly.pdf",type:"app/pdf", size:20000, date:new Date()},
  // {name :"learns to die.img",type:"app/pdf", size:1465, date:new Date()},
  // {name :"learns to lie.cdi",type:"app/pdf", size:8451, date:new Date()},
  // {name :"learns to lie.cdi",type:"app/pdf", size:8451, date:new Date()},
  // {fileName :"learns to lie.cdi",type:"app/pdf", fileDesc:"Nigga", size:8451, date:new Date()},
  // {fileName :"learns to lie.cdi",type:"app/pdf", fileDesc:"Nigga", size:8451, date:new Date()},
  // {fileName :"learns to lie.cdi",type:"app/pdf", fileDesc:"Nigga", size:8451, date:new Date()},
  // {fileName :"learns to lie.cdi",type:"app/pdf", fileDesc:"Nigga", size:8451, date:new Date()}
])




export let mainData = writable([
    {
        _id : "drtgtytdhgfh",
        pic_name : "azrael",
        pic_nip : "817931767",
        pelayanan_kepentingan : "Permintaan sertifikat efaktur mengalami error saat koneksi internet / database gagal dikelola, captcha salah, sertifikat tidak berhasil diimport, kendala jaringan saya bosan hidup dan tidak suka dengan tempat terkutuk ini",
        pelayanan_desc : "Efaktur , registrasi aktivasi efaktur desktop dengan error : ETAX E40005, WP gagal melakukan reset client pada web efaktur (kode aktivasi tidak berubah)) / database gagal dikelola, captcha salah, sertifikat tidak berhasil diimport, kendala jaringan saya bosan hidup dan tidak suka dengan tempat terkutuk ini",
        id_npwp : "815643211712000",
        id_nama: "Abu bakar moment",
        id_alamat : "Jalan Al ikhlas",
        id_nohp : "6285942846251",
        id_nik : "4567456745674567",
        id_klu : "(id_klu 628452) KARYAWAN BRUH MOMENT",
        id_email : "haha@yopmail.com",
        id_kategori : "OP",
        pelayanan_status : "resolved",
        pelayanan_tags : ["id_npwp","EFAKTUR","APLIKASI","ERROR",], 
        pelayanan_reminder : "",
        pelayanan_doc_url : "/2193012y318h812hd21",
        pelayanan_history : [
            {
                _id : "d329hd89n3du2i",
                pic_nip : "810202918",
                time : new Date("2023-08-01"),
                update : "telah dilakukan upload dokumen",
            },
            {
                _id : "81485465215",
                pic_nip : "817931767",
                time : new Date("2023-08-03"),
                update : "registrasi aktivasi efaktur desktop dengan error : ETAX E40005, WP gagal melakukan reset client pada web efaktur database gagal dikelola, captcha salah, sertifikat tidak berhasil diimport, kendala jaringan saya bosan hidup dan tidak suka dengan tempat terkutuk ini",
            },
            {
                _id : "23rgdrg5fgdrg",
                pic_nip : "810202918",
                time : new Date("2023-08-05"),
                update : "semua berhasil yey, njir",
            }
        ]
    },
    
    {
        _id: "dfrg5ydgdfgbd",
        pic_name: "Tax Support Team",
        pic_nip: "817931767",
        pelayanan_kepentingan: "Late Tax Filing",
        pelayanan_desc: "Tax filing for ABC Corp completed successfully.",
        id_npwp: "123456789012345",
        id_nama: "ABC Corporation",
        id_alamat: "789 Oak Avenue, Taxville",
        id_nohp: "6285559876543",
        id_nik: "5678901234567890",
        id_klu: "(id_klu 987123) Corporate Taxpayer",
        id_email: "contact@abccorp.com",
        id_kategori: "Badan",
        pelayanan_status: "resolved",
        pelayanan_tags: ["id_npwp", "TAX FILING", "COMPLETED"],
        pelayanan_reminder: "Submit annual tax report by next month.",
        pelayanan_doc_url: "/348u34uh23kjh24kj",
        pelayanan_history: [
          {  
            _id: "2398r8fn3sdfb3",
            pic_nip: "817931767",
            time: new Date("2023-08-10T09:15:00"),
            update: "Completed tax filing for ABC Corp.",
          },
        ],
      },
      {
        _id: "drgdty4tdrgtdf",
        pic_name: "Tax Consultant",
        pic_nip: "910239488",
        pelayanan_kepentingan: "Tax Audit Report",
        pelayanan_desc: "Tax audit for XYZ Inc successfully resolved.",
        id_npwp: "987654321098765",
        id_nama: "XYZ Inc",
        id_alamat: "101 Maple Street, Taxville",
        id_nohp: "6285551112233",
        id_nik: "1230987654321098",
        id_klu: "(id_klu 567890) Business Entity",
        id_email: "info@xyzinc.com",
        id_kategori: "Badan",
        pelayanan_status: "resolved",
        pelayanan_tags: ["id_npwp", "TAX AUDIT", "RESOLVED"],
        pelayanan_reminder: "Review tax compliance measures.",
        pelayanan_doc_url: "/nwe8h2c78fy32f",
        pelayanan_history: [
          {
            _id: "123jdh230njsdf",
            pic_nip: "910239488",
            time: new Date("2023-08-05T14:30:00"),
            update: "Successfully resolved tax audit for XYZ Inc.",
          },
        ],
      },
      {
        _id: "gdvfgbdtygsrgdfg",
        pic_name: "Tax Advisor",
        pic_nip: "812398712",
        pelayanan_kepentingan: "VAT Refund Request",
        pelayanan_desc: "VAT refund request for Acme Retail completed.",
        id_npwp: "654321098765432",
        id_nama: "Acme Retail",
        id_alamat: "456 Birch Lane, Taxville",
        id_nohp: "6285557778888",
        id_nik: "9876543210123456",
        id_klu: "(id_klu 543210) Retail Business",
        id_email: "acme@example.com",
        id_kategori: "Badan",
        pelayanan_status: "resolved",
        pelayanan_tags: ["id_npwp", "VAT REFUND", "COMPLETED"],
        pelayanan_reminder: "Issue VAT refund payment within 7 days.",
        pelayanan_doc_url: "/123jksdf98q73kdf",
        pelayanan_history: [
          {
            _id: "qw98enfjksldf",
            pic_nip: "812398712",
            time: new Date("2023-08-12T11:45:00"),
            update: "Completed VAT refund request for Acme Retail.",
          },
        ],
      },
      {
        _id: "drgvrgdrvdr",
        pic_name: "Tax Compliance Team",
        pic_nip: "712398472",
        pelayanan_kepentingan: "Tax Penalty Resolution",
        pelayanan_desc: "Penalty dispute for Jackson Enterprises resolved.",
        id_npwp: "345678901234567",
        id_nama: "Jackson Enterprises",
        id_alamat: "789 Pine Street, Taxville",
        id_nohp: "6285554445555",
        id_nik: "1234567890987654",
        id_klu: "(id_klu 901234) Enterprise",
        id_email: "jackson@example.com",
        id_kategori: "Badan",
        pelayanan_status: "resolved",
        pelayanan_tags: ["id_npwp", "PENALTY", "DISPUTE"],
        pelayanan_reminder: "Ensure accurate tax reporting in the future.",
        pelayanan_doc_url: "/908dfh23kdsf38df",
        pelayanan_history: [
          {
            _id: "qwe8923ndjsdf",
            pic_nip: "712398472",
            time: new Date("2023-08-16T16:20:00"),
            update: "Successfully resolved penalty dispute for Jackson Enterprises.",
          },
        ],
      },
      {
        _id: "refdxvtjhgyhd",
        pic_name: "Tax Adviser",
        pic_nip: "812345612",
        pelayanan_kepentingan: "Tax Exemption Request",
        pelayanan_desc: "Approved tax exemption for Green Foundation.",
        id_npwp: "890123456789012",
        id_nama: "Green Foundation",
        id_alamat: "234 Red Road, Taxville",
        id_nohp: "6285556667777",
        id_nik: "9870123456789012",
        id_klu: "(id_klu 345678) Non-profit Organization",
        id_email: "info@greenfoundation.org",
        id_kategori: "Organisasi Non-Profit",
        pelayanan_status: "resolved",
        pelayanan_tags: ["id_npwp", "TAX EXEMPTION", "APPROVED"],
        pelayanan_reminder: "Monitor annual compliance with tax exemption rules.",
        pelayanan_doc_url: "/34hj32h4hj23hj23",
        pelayanan_history: [
          {
            _id: "23n23j4knwskdfn",
            pic_nip: "812345612",
            time: new Date("2023-08-18T13:10:00"),
            update: "Approved tax exemption for Green Foundation.",
          },
        ],
      },
      {
        _id: "5tgthr6ujfyh",
        pic_name: "Tax Adviser",
        pic_nip: "812345612",
        pelayanan_kepentingan: "Tax Exemption Request",
        pelayanan_desc: "Approved tax exemption for Green Foundation.",
        id_npwp: "890123456789012",
        id_nama: "Green Foundation",
        id_alamat: "234 Red Road, Taxville",
        id_nohp: "6285556667777",
        id_nik: "9870123456789012",
        id_klu: "(id_klu 345678) Non-profit Organization",
        id_email: "info@greenfoundation.org",
        id_kategori: "Organisasi Non-Profit",
        pelayanan_status: "resolved",
        pelayanan_tags: ["id_npwp", "TAX EXEMPTION", "APPROVED"],
        pelayanan_reminder: "Monitor annual compliance with tax exemption rules.",
        pelayanan_doc_url: "/34hj32h4hj23hj23",
        pelayanan_history: [
          {
            _id: "23n23j4knwskdfn",
            pic_nip: "812345612",
            time: new Date("2023-08-18T13:10:00"),
            update: "Approved tax exemption for Green Foundation.",
          },
        ],
      },
      {
        _id: "tghrtdgdrg",
        pic_name: "Tax Adviser",
        pic_nip: "812345612",
        pelayanan_kepentingan: "Tax Exemption Request",
        pelayanan_desc: "Approved tax exemption for Green Foundation.",
        id_npwp: "890123456789012",
        id_nama: "Green Foundation",
        id_alamat: "234 Red Road, Taxville",
        id_nohp: "6285556667777",
        id_nik: "9870123456789012",
        id_klu: "(id_klu 345678) Non-profit Organization",
        id_email: "info@greenfoundation.org",
        id_kategori: "Organisasi Non-Profit",
        pelayanan_status: "resolved",
        pelayanan_tags: ["id_npwp", "TAX EXEMPTION", "APPROVED"],
        pelayanan_reminder: "Monitor annual compliance with tax exemption rules.",
        pelayanan_doc_url: "/34hj32h4hj23hj23",
        pelayanan_history: [
          {
            _id: "23n23j4knwskdfn",
            pic_nip: "812345612",
            time: new Date("2023-08-18T13:10:00"),
            update: "Approved tax exemption for Green Foundation.",
          },
        ],
      },
      {
        _id: "yjhfth5tgdfg",
        pic_name: "Tax Adviser",
        pic_nip: "812345612",
        pelayanan_kepentingan: "Tax Exemption Request",
        pelayanan_desc: "Approved tax exemption for Green Foundation.",
        id_npwp: "890123456789012",
        id_nama: "Green Foundation",
        id_alamat: "234 Red Road, Taxville",
        id_nohp: "6285556667777",
        id_nik: "9870123456789012",
        id_klu: "(id_klu 345678) Non-profit Organization",
        id_email: "info@greenfoundation.org",
        id_kategori: "Organisasi Non-Profit",
        pelayanan_status: "resolved",
        pelayanan_tags: ["id_npwp", "TAX EXEMPTION", "APPROVED"],
        pelayanan_reminder: "Monitor annual compliance with tax exemption rules.",
        pelayanan_doc_url: "/34hj32h4hj23hj23",
        pelayanan_history: [
          {
            _id: "23n23j4knwskdfn",
            pic_nip: "812345612",
            time: new Date("2023-08-18T13:10:00"),
            update: "Approved tax exemption for Green Foundation.",
          },
        ],
      },
      {
        _id: "ftyhth6dfgth",
        pic_name: "Tax Adviser",
        pic_nip: "812345612",
        pelayanan_kepentingan: "Tax Exemption Request",
        pelayanan_desc: "Approved tax exemption for Green Foundation.",
        id_npwp: "890123456789012",
        id_nama: "Green Foundation",
        id_alamat: "234 Red Road, Taxville",
        id_nohp: "6285556667777",
        id_nik: "9870123456789012",
        id_klu: "(id_klu 345678) Non-profit Organization",
        id_email: "info@greenfoundation.org",
        id_kategori: "Organisasi Non-Profit",
        pelayanan_status: "resolved",
        pelayanan_tags: ["id_npwp", "TAX EXEMPTION", "APPROVED"],
        pelayanan_reminder: "Monitor annual compliance with tax exemption rules.",
        pelayanan_doc_url: "/34hj32h4hj23hj23",
        pelayanan_history: [
          {
            _id: "23n23j4knwskdfn",
            pic_nip: "812345612",
            time: new Date("2023-08-18T13:10:00"),
            update: "Approved tax exemption for Green Foundation.",
          },
        ],
      },
      {
        _id: "gdtgdtgdrgd",
        pic_name: "Tax Adviser",
        pic_nip: "812345612",
        pelayanan_kepentingan: "Tax Exemption Request",
        pelayanan_desc: "Approved tax exemption for Green Foundation.",
        id_npwp: "890123456789012",
        id_nama: "Green Foundation",
        id_alamat: "234 Red Road, Taxville",
        id_nohp: "6285556667777",
        id_nik: "9870123456789012",
        id_klu: "(id_klu 345678) Non-profit Organization",
        id_email: "info@greenfoundation.org",
        id_kategori: "Organisasi Non-Profit",
        pelayanan_status: "resolved",
        pelayanan_tags: ["id_npwp", "TAX EXEMPTION", "APPROVED"],
        pelayanan_reminder: "Monitor annual compliance with tax exemption rules.",
        pelayanan_doc_url: "/34hj32h4hj23hj23",
        pelayanan_history: [
          {
            _id: "23n23j4knwskdfn",
            pic_nip: "812345612",
            time: new Date("2023-08-18T13:10:00"),
            update: "Approved tax exemption for Green Foundation.",
          },
        ],
      },
      {
        _id: "yjfgbsfr",
        pic_name: "Tax Adviser",
        pic_nip: "812345612",
        pelayanan_kepentingan: "Tax Exemption Request",
        pelayanan_desc: "Approved tax exemption for Green Foundation.",
        id_npwp: "890123456789012",
        id_nama: "Green Foundation",
        id_alamat: "234 Red Road, Taxville",
        id_nohp: "6285556667777",
        id_nik: "9870123456789012",
        id_klu: "(id_klu 345678) Non-profit Organization",
        id_email: "info@greenfoundation.org",
        id_kategori: "Organisasi Non-Profit",
        pelayanan_status: "resolved",
        pelayanan_tags: ["id_npwp", "TAX EXEMPTION", "APPROVED"],
        pelayanan_reminder: "Monitor annual compliance with tax exemption rules.",
        pelayanan_doc_url: "/34hj32h4hj23hj23",
        pelayanan_history: [
          {
            _id: "23n23j4knwskdfn",
            pic_nip: "812345612",
            time: new Date("2023-08-18T13:10:00"),
            update: "Approved tax exemption for Green Foundation.",
          },
        ],
      },
      {
        _id: "5dgfgdgdfgdf",
        pic_name: "Tax Adviser",
        pic_nip: "812345612",
        pelayanan_kepentingan: "Tax Exemption Request",
        pelayanan_desc: "Approved tax exemption for Green Foundation.",
        id_npwp: "890123456789012",
        id_nama: "Green Foundation",
        id_alamat: "234 Red Road, Taxville",
        id_nohp: "6285556667777",
        id_nik: "9870123456789012",
        id_klu: "(id_klu 345678) Non-profit Organization",
        id_email: "info@greenfoundation.org",
        id_kategori: "Organisasi Non-Profit",
        pelayanan_status: "resolved",
        pelayanan_tags: ["id_npwp", "TAX EXEMPTION", "APPROVED"],
        pelayanan_reminder: "Monitor annual compliance with tax exemption rules.",
        pelayanan_doc_url: "/34hj32h4hj23hj23",
        pelayanan_history: [
          {
            _id: "23n23j4knwskdfn",
            pic_nip: "812345612",
            time: new Date("2023-08-18T13:10:00"),
            update: "Approved tax exemption for Green Foundation.",
          },
        ],
      },
      {
        _id: "rgdrgvdrgdfgdfg",
        pic_name: "Tax Adviser",
        pic_nip: "812345612",
        pelayanan_kepentingan: "Tax Exemption Request",
        pelayanan_desc: "Approved tax exemption for Green Foundation.",
        id_npwp: "890123456789012",
        id_nama: "Green Foundation",
        id_alamat: "234 Red Road, Taxville",
        id_nohp: "6285556667777",
        id_nik: "9870123456789012",
        id_klu: "(id_klu 345678) Non-profit Organization",
        id_email: "info@greenfoundation.org",
        id_kategori: "Organisasi Non-Profit",
        pelayanan_status: "resolved",
        pelayanan_tags: ["id_npwp", "TAX EXEMPTION", "APPROVED"],
        pelayanan_reminder: "Monitor annual compliance with tax exemption rules.",
        pelayanan_doc_url: "/34hj32h4hj23hj23",
        pelayanan_history: [
          {
            _id: "23n23j4knwskdfn",
            pic_nip: "812345612",
            time: new Date("2023-08-18T13:10:00"),
            update: "Approved tax exemption for Green Foundation.",
          },
        ],
      },
      {
        _id: "ger5gdrgdrgdrg",
        pic_name: "Tax Adviser",
        pic_nip: "812345612",
        pelayanan_kepentingan: "Tax Exemption Request",
        pelayanan_desc: "Approved tax exemption for Green Foundation.",
        id_npwp: "890123456789012",
        id_nama: "Green Foundation",
        id_alamat: "234 Red Road, Taxville",
        id_nohp: "6285556667777",
        id_nik: "9870123456789012",
        id_klu: "(id_klu 345678) Non-profit Organization",
        id_email: "info@greenfoundation.org",
        id_kategori: "Organisasi Non-Profit",
        pelayanan_status: "resolved",
        pelayanan_tags: ["id_npwp", "TAX EXEMPTION", "APPROVED"],
        pelayanan_reminder: "Monitor annual compliance with tax exemption rules.",
        pelayanan_doc_url: "/34hj32h4hj23hj23",
        pelayanan_history: [
          {
            _id: "23n23j4knwskdfn",
            pic_nip: "812345612",
            time: new Date("2023-08-18T13:10:00"),
            update: "Approved tax exemption for Green Foundation.",
          },
        ],
      },
      {
        _id: "g5grv4grgdrfg",
        pic_name: "Tax Adviser",
        pic_nip: "812345612",
        pelayanan_kepentingan: "Tax Exemption Request",
        pelayanan_desc: "Approved tax exemption for Green Foundation.",
        id_npwp: "890123456789012",
        id_nama: "Green Foundation",
        id_alamat: "234 Red Road, Taxville",
        id_nohp: "6285556667777",
        id_nik: "9870123456789012",
        id_klu: "(id_klu 345678) Non-profit Organization",
        id_email: "info@greenfoundation.org",
        id_kategori: "Organisasi Non-Profit",
        pelayanan_status: "resolved",
        pelayanan_tags: ["id_npwp", "TAX EXEMPTION", "APPROVED"],
        pelayanan_reminder: "Monitor annual compliance with tax exemption rules.",
        pelayanan_doc_url: "/34hj32h4hj23hj23",
        pelayanan_history: [
          {
            _id: "23n23j4knwskdfn",
            pic_nip: "812345612",
            time: new Date("2023-08-18T13:10:00"),
            update: "Approved tax exemption for Green Foundation.",
          },
        ],
      },
      {
        _id: "geg5evege5ge5g5e",
        pic_name: "Tax Adviser",
        pic_nip: "812345612",
        pelayanan_kepentingan: "Tax Exemption Request",
        pelayanan_desc: "Approved tax exemption for Green Foundation.",
        id_npwp: "890123456789012",
        id_nama: "Green Foundation",
        id_alamat: "234 Red Road, Taxville",
        id_nohp: "6285556667777",
        id_nik: "9870123456789012",
        id_klu: "(id_klu 345678) Non-profit Organization",
        id_email: "info@greenfoundation.org",
        id_kategori: "Organisasi Non-Profit",
        pelayanan_status: "resolved",
        pelayanan_tags: ["id_npwp", "TAX EXEMPTION", "APPROVED"],
        pelayanan_reminder: "Monitor annual compliance with tax exemption rules.",
        pelayanan_doc_url: "/34hj32h4hj23hj23",
        pelayanan_history: [
          {
            _id: "23n23j4knwskdfn",
            pic_nip: "812345612",
            time: new Date("2023-08-18T13:10:00"),
            update: "Approved tax exemption for Green Foundation.",
          },
        ],
      },
      {
        _id: "gge5ge5ge5",
        pic_name: "Tax Adviser",
        pic_nip: "812345612",
        pelayanan_kepentingan: "Tax Exemption Request",
        pelayanan_desc: "Approved tax exemption for Green Foundation.",
        id_npwp: "890123456789012",
        id_nama: "Green Foundation",
        id_alamat: "234 Red Road, Taxville",
        id_nohp: "6285556667777",
        id_nik: "9870123456789012",
        id_klu: "(id_klu 345678) Non-profit Organization",
        id_email: "info@greenfoundation.org",
        id_kategori: "Organisasi Non-Profit",
        pelayanan_status: "resolved",
        pelayanan_tags: ["id_npwp", "TAX EXEMPTION", "APPROVED"],
        pelayanan_reminder: "Monitor annual compliance with tax exemption rules.",
        pelayanan_doc_url: "/34hj32h4hj23hj23",
        pelayanan_history: [
          {
            _id: "23n23j4knwskdfn",
            pic_nip: "812345612",
            time: new Date("2023-08-18T13:10:00"),
            update: "Approved tax exemption for Green Foundation.",
          },
        ],
      },

])