import { writable } from "svelte/store";

export let totalRec = writable(19)
export let pegawaiContext = writable(false)



export let petugas_context = writable(false)
export let petugas_value = writable('all')

export let resolvedData = writable([
    {
        _id : "drtgtytdhgfh",
        pic : "azrael",
        nip_pic : "817931767",
        kepentingan : "Permintaan sertifikat efaktur mengalami error saat koneksi internet / database gagal dikelola, captcha salah, sertifikat tidak berhasil diimport, kendala jaringan saya bosan hidup dan tidak suka dengan tempat terkutuk ini",
        desc : "Efaktur , registrasi aktivasi efaktur desktop dengan error : ETAX E40005, WP gagal melakukan reset client pada web efaktur (kode aktivasi tidak berubah)) / database gagal dikelola, captcha salah, sertifikat tidak berhasil diimport, kendala jaringan saya bosan hidup dan tidak suka dengan tempat terkutuk ini",
        npwp : "815643211712000",
        nama_wp: "Abu bakar moment",
        alamat : "Jalan Al ikhlas",
        nohp : "6285942846251",
        nik : "4567456745674567",
        klu : "(KLU 628452) KARYAWAN BRUH MOMENT",
        email : "haha@yopmail.com",
        kategori : "OP",
        status : "resolved",
        tags : ["NPWP","EFAKTUR","APLIKASI","ERROR",], 
        reminder : "",
        documents_url : "/2193012y318h812hd21",
        history : [
            {
                _id : "d329hd89n3du2i",
                nip_pic : "810202918",
                time : new Date("2023-08-01"),
                update : "telah dilakukan upload dokumen",
            },
            {
                _id : "81485465215",
                nip_pic : "817931767",
                time : new Date("2023-08-03"),
                update : "registrasi aktivasi efaktur desktop dengan error : ETAX E40005, WP gagal melakukan reset client pada web efaktur database gagal dikelola, captcha salah, sertifikat tidak berhasil diimport, kendala jaringan saya bosan hidup dan tidak suka dengan tempat terkutuk ini",
            },
            {
                _id : "23rgdrg5fgdrg",
                nip_pic : "810202918",
                time : new Date("2023-08-05"),
                update : "semua berhasil yey, njir",
            }
        ]
    },
    {
        _id: "dfrg5ydgdfgbd",
        pic: "Tax Support Team",
        nip_pic: "817931767",
        kepentingan: "Late Tax Filing",
        desc: "Tax filing for ABC Corp completed successfully.",
        npwp: "123456789012345",
        nama_wp: "ABC Corporation",
        alamat: "789 Oak Avenue, Taxville",
        nohp: "6285559876543",
        nik: "5678901234567890",
        klu: "(KLU 987123) Corporate Taxpayer",
        email: "contact@abccorp.com",
        kategori: "Badan",
        status: "resolved",
        tags: ["NPWP", "TAX FILING", "COMPLETED"],
        reminder: "Submit annual tax report by next month.",
        documents_url: "/348u34uh23kjh24kj",
        history: [
          {  
            _id: "2398r8fn3sdfb3",
            nip_pic: "817931767",
            time: new Date("2023-08-10T09:15:00"),
            update: "Completed tax filing for ABC Corp.",
          },
        ],
      },
      {
        _id: "drgdty4tdrgtdf",
        pic: "Tax Consultant",
        nip_pic: "910239488",
        kepentingan: "Tax Audit Report",
        desc: "Tax audit for XYZ Inc successfully resolved.",
        npwp: "987654321098765",
        nama_wp: "XYZ Inc",
        alamat: "101 Maple Street, Taxville",
        nohp: "6285551112233",
        nik: "1230987654321098",
        klu: "(KLU 567890) Business Entity",
        email: "info@xyzinc.com",
        kategori: "Badan",
        status: "resolved",
        tags: ["NPWP", "TAX AUDIT", "RESOLVED"],
        reminder: "Review tax compliance measures.",
        documents_url: "/nwe8h2c78fy32f",
        history: [
          {
            _id: "123jdh230njsdf",
            nip_pic: "910239488",
            time: new Date("2023-08-05T14:30:00"),
            update: "Successfully resolved tax audit for XYZ Inc.",
          },
        ],
      },
      {
        _id: "gdvfgbdtygsrgdfg",
        pic: "Tax Advisor",
        nip_pic: "812398712",
        kepentingan: "VAT Refund Request",
        desc: "VAT refund request for Acme Retail completed.",
        npwp: "654321098765432",
        nama_wp: "Acme Retail",
        alamat: "456 Birch Lane, Taxville",
        nohp: "6285557778888",
        nik: "9876543210123456",
        klu: "(KLU 543210) Retail Business",
        email: "acme@example.com",
        kategori: "Badan",
        status: "resolved",
        tags: ["NPWP", "VAT REFUND", "COMPLETED"],
        reminder: "Issue VAT refund payment within 7 days.",
        documents_url: "/123jksdf98q73kdf",
        history: [
          {
            _id: "qw98enfjksldf",
            nip_pic: "812398712",
            time: new Date("2023-08-12T11:45:00"),
            update: "Completed VAT refund request for Acme Retail.",
          },
        ],
      },
      {
        _id: "drgvrgdrvdr",
        pic: "Tax Compliance Team",
        nip_pic: "712398472",
        kepentingan: "Tax Penalty Resolution",
        desc: "Penalty dispute for Jackson Enterprises resolved.",
        npwp: "345678901234567",
        nama_wp: "Jackson Enterprises",
        alamat: "789 Pine Street, Taxville",
        nohp: "6285554445555",
        nik: "1234567890987654",
        klu: "(KLU 901234) Enterprise",
        email: "jackson@example.com",
        kategori: "Badan",
        status: "resolved",
        tags: ["NPWP", "PENALTY", "DISPUTE"],
        reminder: "Ensure accurate tax reporting in the future.",
        documents_url: "/908dfh23kdsf38df",
        history: [
          {
            _id: "qwe8923ndjsdf",
            nip_pic: "712398472",
            time: new Date("2023-08-16T16:20:00"),
            update: "Successfully resolved penalty dispute for Jackson Enterprises.",
          },
        ],
      },
      {
        _id: "refdxvtjhgyhd",
        pic: "Tax Adviser",
        nip_pic: "812345612",
        kepentingan: "Tax Exemption Request",
        desc: "Approved tax exemption for Green Foundation.",
        npwp: "890123456789012",
        nama_wp: "Green Foundation",
        alamat: "234 Red Road, Taxville",
        nohp: "6285556667777",
        nik: "9870123456789012",
        klu: "(KLU 345678) Non-profit Organization",
        email: "info@greenfoundation.org",
        kategori: "Organisasi Non-Profit",
        status: "resolved",
        tags: ["NPWP", "TAX EXEMPTION", "APPROVED"],
        reminder: "Monitor annual compliance with tax exemption rules.",
        documents_url: "/34hj32h4hj23hj23",
        history: [
          {
            _id: "23n23j4knwskdfn",
            nip_pic: "812345612",
            time: new Date("2023-08-18T13:10:00"),
            update: "Approved tax exemption for Green Foundation.",
          },
        ],
      },
      {
        _id: "5tgthr6ujfyh",
        pic: "Tax Adviser",
        nip_pic: "812345612",
        kepentingan: "Tax Exemption Request",
        desc: "Approved tax exemption for Green Foundation.",
        npwp: "890123456789012",
        nama_wp: "Green Foundation",
        alamat: "234 Red Road, Taxville",
        nohp: "6285556667777",
        nik: "9870123456789012",
        klu: "(KLU 345678) Non-profit Organization",
        email: "info@greenfoundation.org",
        kategori: "Organisasi Non-Profit",
        status: "resolved",
        tags: ["NPWP", "TAX EXEMPTION", "APPROVED"],
        reminder: "Monitor annual compliance with tax exemption rules.",
        documents_url: "/34hj32h4hj23hj23",
        history: [
          {
            _id: "23n23j4knwskdfn",
            nip_pic: "812345612",
            time: new Date("2023-08-18T13:10:00"),
            update: "Approved tax exemption for Green Foundation.",
          },
        ],
      },
      {
        _id: "tghrtdgdrg",
        pic: "Tax Adviser",
        nip_pic: "812345612",
        kepentingan: "Tax Exemption Request",
        desc: "Approved tax exemption for Green Foundation.",
        npwp: "890123456789012",
        nama_wp: "Green Foundation",
        alamat: "234 Red Road, Taxville",
        nohp: "6285556667777",
        nik: "9870123456789012",
        klu: "(KLU 345678) Non-profit Organization",
        email: "info@greenfoundation.org",
        kategori: "Organisasi Non-Profit",
        status: "resolved",
        tags: ["NPWP", "TAX EXEMPTION", "APPROVED"],
        reminder: "Monitor annual compliance with tax exemption rules.",
        documents_url: "/34hj32h4hj23hj23",
        history: [
          {
            _id: "23n23j4knwskdfn",
            nip_pic: "812345612",
            time: new Date("2023-08-18T13:10:00"),
            update: "Approved tax exemption for Green Foundation.",
          },
        ],
      },
      {
        _id: "yjhfth5tgdfg",
        pic: "Tax Adviser",
        nip_pic: "812345612",
        kepentingan: "Tax Exemption Request",
        desc: "Approved tax exemption for Green Foundation.",
        npwp: "890123456789012",
        nama_wp: "Green Foundation",
        alamat: "234 Red Road, Taxville",
        nohp: "6285556667777",
        nik: "9870123456789012",
        klu: "(KLU 345678) Non-profit Organization",
        email: "info@greenfoundation.org",
        kategori: "Organisasi Non-Profit",
        status: "resolved",
        tags: ["NPWP", "TAX EXEMPTION", "APPROVED"],
        reminder: "Monitor annual compliance with tax exemption rules.",
        documents_url: "/34hj32h4hj23hj23",
        history: [
          {
            _id: "23n23j4knwskdfn",
            nip_pic: "812345612",
            time: new Date("2023-08-18T13:10:00"),
            update: "Approved tax exemption for Green Foundation.",
          },
        ],
      },
      {
        _id: "ftyhth6dfgth",
        pic: "Tax Adviser",
        nip_pic: "812345612",
        kepentingan: "Tax Exemption Request",
        desc: "Approved tax exemption for Green Foundation.",
        npwp: "890123456789012",
        nama_wp: "Green Foundation",
        alamat: "234 Red Road, Taxville",
        nohp: "6285556667777",
        nik: "9870123456789012",
        klu: "(KLU 345678) Non-profit Organization",
        email: "info@greenfoundation.org",
        kategori: "Organisasi Non-Profit",
        status: "resolved",
        tags: ["NPWP", "TAX EXEMPTION", "APPROVED"],
        reminder: "Monitor annual compliance with tax exemption rules.",
        documents_url: "/34hj32h4hj23hj23",
        history: [
          {
            _id: "23n23j4knwskdfn",
            nip_pic: "812345612",
            time: new Date("2023-08-18T13:10:00"),
            update: "Approved tax exemption for Green Foundation.",
          },
        ],
      },
      {
        _id: "gdtgdtgdrgd",
        pic: "Tax Adviser",
        nip_pic: "812345612",
        kepentingan: "Tax Exemption Request",
        desc: "Approved tax exemption for Green Foundation.",
        npwp: "890123456789012",
        nama_wp: "Green Foundation",
        alamat: "234 Red Road, Taxville",
        nohp: "6285556667777",
        nik: "9870123456789012",
        klu: "(KLU 345678) Non-profit Organization",
        email: "info@greenfoundation.org",
        kategori: "Organisasi Non-Profit",
        status: "resolved",
        tags: ["NPWP", "TAX EXEMPTION", "APPROVED"],
        reminder: "Monitor annual compliance with tax exemption rules.",
        documents_url: "/34hj32h4hj23hj23",
        history: [
          {
            _id: "23n23j4knwskdfn",
            nip_pic: "812345612",
            time: new Date("2023-08-18T13:10:00"),
            update: "Approved tax exemption for Green Foundation.",
          },
        ],
      },
      {
        _id: "yjfgbsfr",
        pic: "Tax Adviser",
        nip_pic: "812345612",
        kepentingan: "Tax Exemption Request",
        desc: "Approved tax exemption for Green Foundation.",
        npwp: "890123456789012",
        nama_wp: "Green Foundation",
        alamat: "234 Red Road, Taxville",
        nohp: "6285556667777",
        nik: "9870123456789012",
        klu: "(KLU 345678) Non-profit Organization",
        email: "info@greenfoundation.org",
        kategori: "Organisasi Non-Profit",
        status: "resolved",
        tags: ["NPWP", "TAX EXEMPTION", "APPROVED"],
        reminder: "Monitor annual compliance with tax exemption rules.",
        documents_url: "/34hj32h4hj23hj23",
        history: [
          {
            _id: "23n23j4knwskdfn",
            nip_pic: "812345612",
            time: new Date("2023-08-18T13:10:00"),
            update: "Approved tax exemption for Green Foundation.",
          },
        ],
      },
      {
        _id: "5dgfgdgdfgdf",
        pic: "Tax Adviser",
        nip_pic: "812345612",
        kepentingan: "Tax Exemption Request",
        desc: "Approved tax exemption for Green Foundation.",
        npwp: "890123456789012",
        nama_wp: "Green Foundation",
        alamat: "234 Red Road, Taxville",
        nohp: "6285556667777",
        nik: "9870123456789012",
        klu: "(KLU 345678) Non-profit Organization",
        email: "info@greenfoundation.org",
        kategori: "Organisasi Non-Profit",
        status: "resolved",
        tags: ["NPWP", "TAX EXEMPTION", "APPROVED"],
        reminder: "Monitor annual compliance with tax exemption rules.",
        documents_url: "/34hj32h4hj23hj23",
        history: [
          {
            _id: "23n23j4knwskdfn",
            nip_pic: "812345612",
            time: new Date("2023-08-18T13:10:00"),
            update: "Approved tax exemption for Green Foundation.",
          },
        ],
      },
      {
        _id: "rgdrgvdrgdfgdfg",
        pic: "Tax Adviser",
        nip_pic: "812345612",
        kepentingan: "Tax Exemption Request",
        desc: "Approved tax exemption for Green Foundation.",
        npwp: "890123456789012",
        nama_wp: "Green Foundation",
        alamat: "234 Red Road, Taxville",
        nohp: "6285556667777",
        nik: "9870123456789012",
        klu: "(KLU 345678) Non-profit Organization",
        email: "info@greenfoundation.org",
        kategori: "Organisasi Non-Profit",
        status: "resolved",
        tags: ["NPWP", "TAX EXEMPTION", "APPROVED"],
        reminder: "Monitor annual compliance with tax exemption rules.",
        documents_url: "/34hj32h4hj23hj23",
        history: [
          {
            _id: "23n23j4knwskdfn",
            nip_pic: "812345612",
            time: new Date("2023-08-18T13:10:00"),
            update: "Approved tax exemption for Green Foundation.",
          },
        ],
      },
      {
        _id: "ger5gdrgdrgdrg",
        pic: "Tax Adviser",
        nip_pic: "812345612",
        kepentingan: "Tax Exemption Request",
        desc: "Approved tax exemption for Green Foundation.",
        npwp: "890123456789012",
        nama_wp: "Green Foundation",
        alamat: "234 Red Road, Taxville",
        nohp: "6285556667777",
        nik: "9870123456789012",
        klu: "(KLU 345678) Non-profit Organization",
        email: "info@greenfoundation.org",
        kategori: "Organisasi Non-Profit",
        status: "resolved",
        tags: ["NPWP", "TAX EXEMPTION", "APPROVED"],
        reminder: "Monitor annual compliance with tax exemption rules.",
        documents_url: "/34hj32h4hj23hj23",
        history: [
          {
            _id: "23n23j4knwskdfn",
            nip_pic: "812345612",
            time: new Date("2023-08-18T13:10:00"),
            update: "Approved tax exemption for Green Foundation.",
          },
        ],
      },
      {
        _id: "g5grv4grgdrfg",
        pic: "Tax Adviser",
        nip_pic: "812345612",
        kepentingan: "Tax Exemption Request",
        desc: "Approved tax exemption for Green Foundation.",
        npwp: "890123456789012",
        nama_wp: "Green Foundation",
        alamat: "234 Red Road, Taxville",
        nohp: "6285556667777",
        nik: "9870123456789012",
        klu: "(KLU 345678) Non-profit Organization",
        email: "info@greenfoundation.org",
        kategori: "Organisasi Non-Profit",
        status: "resolved",
        tags: ["NPWP", "TAX EXEMPTION", "APPROVED"],
        reminder: "Monitor annual compliance with tax exemption rules.",
        documents_url: "/34hj32h4hj23hj23",
        history: [
          {
            _id: "23n23j4knwskdfn",
            nip_pic: "812345612",
            time: new Date("2023-08-18T13:10:00"),
            update: "Approved tax exemption for Green Foundation.",
          },
        ],
      },
      {
        _id: "geg5evege5ge5g5e",
        pic: "Tax Adviser",
        nip_pic: "812345612",
        kepentingan: "Tax Exemption Request",
        desc: "Approved tax exemption for Green Foundation.",
        npwp: "890123456789012",
        nama_wp: "Green Foundation",
        alamat: "234 Red Road, Taxville",
        nohp: "6285556667777",
        nik: "9870123456789012",
        klu: "(KLU 345678) Non-profit Organization",
        email: "info@greenfoundation.org",
        kategori: "Organisasi Non-Profit",
        status: "resolved",
        tags: ["NPWP", "TAX EXEMPTION", "APPROVED"],
        reminder: "Monitor annual compliance with tax exemption rules.",
        documents_url: "/34hj32h4hj23hj23",
        history: [
          {
            _id: "23n23j4knwskdfn",
            nip_pic: "812345612",
            time: new Date("2023-08-18T13:10:00"),
            update: "Approved tax exemption for Green Foundation.",
          },
        ],
      },
      {
        _id: "gge5ge5ge5",
        pic: "Tax Adviser",
        nip_pic: "812345612",
        kepentingan: "Tax Exemption Request",
        desc: "Approved tax exemption for Green Foundation.",
        npwp: "890123456789012",
        nama_wp: "Green Foundation",
        alamat: "234 Red Road, Taxville",
        nohp: "6285556667777",
        nik: "9870123456789012",
        klu: "(KLU 345678) Non-profit Organization",
        email: "info@greenfoundation.org",
        kategori: "Organisasi Non-Profit",
        status: "resolved",
        tags: ["NPWP", "TAX EXEMPTION", "APPROVED"],
        reminder: "Monitor annual compliance with tax exemption rules.",
        documents_url: "/34hj32h4hj23hj23",
        history: [
          {
            _id: "23n23j4knwskdfn",
            nip_pic: "812345612",
            time: new Date("2023-08-18T13:10:00"),
            update: "Approved tax exemption for Green Foundation.",
          },
        ],
      },

])